### ISSUE TITLE
Lemonway::Client::Error: 138 : This feature is not available

### ISSUE THREAD

**Issue by gponsu** [lemonwaysas/ruby-client-directkit-string#5]
Good morning,

I have a problem when I try registrater a card.

When I create a wallet, it works perfect:

``` ruby
client = Lemonway::Client.new wsdl: "https://sandbox-api.lemonway.fr/mb/#{mycompany}/dev/directkitxml/service.asmx?wsdl", wl_login: "society", wl_pass: "123456", language: "en", version: "1.2", wallet_ip: "#{my_authorized_ip}" do |opts|
   opts.ssl_verify_mode(:none)
end  
```

``` ruby
wallet = client.register_wallet wallet: "123456789", client_mail: "john@email.com", client_first_name: "john", client_last_name: "doe"
=> {"id"=>"123456789", "lwid"=>"27"}
```

But if I try to add a card, I get this error:

``` ruby
card = client.register_card(wallet: '123456789', card_type: "1", card_number: "5017670000006700", card_code: "123", card_date: "12/2016")
```

``` bash
Lemonway::Client::Error: 138 : This feature is not available
    from /app/.bundle/gems/lemonway-1.0.1/lib/lemonway/client.rb:45:in `client_call'
    from /app/.bundle/gems/lemonway-1.0.1/lib/lemonway/client.rb:29:in `method_missing'
    from (irb):170
    from /app/.bundle/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
    from /app/.bundle/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
    from /app/.bundle/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /app/.bundle/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /app/.bundle/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /app/bin/rails:9:in `<top (required)>'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /app/.bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'

```

I tested with different card numbers that I found in the documentation: http://documentation.lemonway.fr/api-en/introduction/test-environment-and-default-accounts

What am I doing wrong?

Thank you very much, a greeting!

**Comment by pham-dat** [comment]
Hi gponsu,

Actually we've got a problem with the PSP. We are fixing it for all of our partners.
Could you give me the name of your company so we can fix it in priority?

Kind Regards

**Comment by gponsu** [comment]
The name of my company is Splitfy,

Thank you very much!

**Comment by pham-dat** [comment]
We've fixed it for you. Please try again.

**Comment by gponsu** [comment]
Thank you very much, it works :)
